export const retireData2020 = {
  2011: {
    retirementCount: 7,
    baseCount: 1913,
    retirementPercentage: 0.4,
  },
  2012: {
    retirementCount: 63,
    baseCount: 2008,
    retirementPercentage: 3.1,
  },
  2013: {
    retirementCount: 0,
    baseCount: 2137,
    retirementPercentage: 0,
  },
  2014: {
    retirementCount: 4,
    baseCount: 2214,
    retirementPercentage: 0.2,
  },
  2015: {
    retirementCount: 4,
    baseCount: 2327,
    retirementPercentage: 0.2,
  },
  2016: {
    retirementCount: 2,
    baseCount: 2424,
    retirementPercentage: 0.1,
  },
  2017: {
    retirementCount: 1,
    baseCount: 2466,
    retirementPercentage: 0,
  },
  2018: {
    retirementCount: 1,
    baseCount: 2468,
    retirementPercentage: 0,
  },
  2019: {
    retirementCount: 1,
    baseCount: 2480,
    retirementPercentage: 0,
  },
  2020: {
    retirementCount: 22,
    baseCount: 2676,
    retirementPercentage: 0.8,
  },
};

export const retireData2022 = {
  2013: {
    retirementCount: 0,
    baseCount: 2137,
    retirementPercentage: 0,
  },
  2014: {
    retirementCount: 4,
    baseCount: 2214,
    retirementPercentage: 0.2,
  },
  2015: {
    retirementCount: 4,
    baseCount: 2327,
    retirementPercentage: 0.2,
  },
  2016: {
    retirementCount: 2,
    baseCount: 2424,
    retirementPercentage: 0.1,
  },
  2017: {
    retirementCount: 1,
    baseCount: 2466,
    retirementPercentage: 0,
  },
  2018: {
    retirementCount: 1,
    baseCount: 2468,
    retirementPercentage: 0,
  },
  2019: {
    retirementCount: 1,
    baseCount: 2480,
    retirementPercentage: 0,
  },
  2020: {
    retirementCount: 22,
    baseCount: 2676,
    retirementPercentage: 0.8,
  },
  2021: {
    retirementCount: 146,
    baseCount: 3134,
    retirementPercentage: 4.7,
  },
  2022: {
    retirementCount: 47,
    baseCount: 4095,
    retirementPercentage: 1.1,
  },
};

export const retireData2021 = {
  2012: {
    retirementCount: 63,
    baseCount: 2008,
    retirementPercentage: 3.1,
  },
  2013: {
    retirementCount: 0,
    baseCount: 2137,
    retirementPercentage: 0,
  },
  2014: {
    retirementCount: 4,
    baseCount: 2214,
    retirementPercentage: 0.2,
  },
  2015: {
    retirementCount: 4,
    baseCount: 2327,
    retirementPercentage: 0.2,
  },
  2016: {
    retirementCount: 2,
    baseCount: 2424,
    retirementPercentage: 0.1,
  },
  2017: {
    retirementCount: 1,
    baseCount: 2466,
    retirementPercentage: 0,
  },
  2018: {
    retirementCount: 1,
    baseCount: 2468,
    retirementPercentage: 0,
  },
  2019: {
    retirementCount: 1,
    baseCount: 2480,
    retirementPercentage: 0,
  },
  2020: {
    retirementCount: 22,
    baseCount: 2676,
    retirementPercentage: 0.8,
  },
  2021: {
    retirementCount: 146,
    baseCount: 3134,
    retirementPercentage: 4.7,
  },
};
